### ISSUE TITLE
Response code?

### ISSUE THREAD

**Issue by PascalLeMerrer** [egorzhdan/networkinkt#2]
Hello

How do you get the http status of the response?

**Comment by egorzhdan** [comment]
As for now it will throw an `HTTPException` if the response code is not 2XX.
The exception object has an integer `code` field.

I will make this more transparent & customisable some time soon.

**Comment by egorzhdan** [comment]
I've published a new release with API changes.
You can now more conveniently get the response code from an `HTTPResponse` object.

For more info, please take a look at [usage](https://github.com/egorzhdan/networkinkt#usage)
